//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkWithSQLite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Director { get; set; }
        public long Playtime { get; set; }

		/// <summary>
		/// Initialisize object
		/// </summary>
		public Movies()
		{ }

		/// <summary>
		/// Initialisize object with data
		/// </summary>
		/// <param name="name"></param>
		/// <param name="director"></param>
		/// <param name="playtime"></param>
		public Movies(string name, string director, long playtime)
		{
			Name = name;
			Director = director;
			Playtime = playtime;
		}
    }
}
